# Generated by Django 3.2 on 2022-05-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/posts/%Y/%m/%d/'),
        ),
    ]
